baseURL = "https://ciceroni.netlify.app/"
canonifyURLs = false
languageCode = "en-us"
title = "Ciceroni"
copyright = "Copyright © 2022 Ciceroni"
paginate = 9
mainSections = ["blog"]
enableRobotsTXT = true
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
timeout = "60s"

# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["nl"]
DefaultContentLanguageInSubdir = false

[taxonomies]
  tag = 'tags'

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true


[outputFormats]
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.108.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"

